"""Restricted exec() sandbox for running generated remediation code.

Filled in during Week 3. Must run with no filesystem/network access
beyond the mock remediation client provided by Person A.
"""


def run_sandboxed(code: str, allowed_globals: dict) -> None:
    """Execute generated code in a restricted environment.

    Args:
        code: Python source generated by codegen.py.
        allowed_globals: restricted globals dict (mock client, builtins subset).
    """
    raise NotImplementedError("sandbox: implemented in Week 3")
