"""Restricted exec() sandbox for running generated remediation code.

Runs code produced by codegen.py against a small allowlist of mock
remediation functions (currently Person A's placeholder in
mock_methods.py — see that file's docstring), with restricted builtins
so generated code cannot touch the filesystem, network, or import
anything beyond what's explicitly allowed.

This is a defense-in-depth measure, not a full Python sandbox — CPython
has no fully secure exec() sandbox; determined code with access to
object internals (e.g. via __class__.__bases__) can sometimes escape
restricted-builtins sandboxes. This is considered acceptable here
because the code being run is not arbitrary user input — it's generated
by codegen.py from a fixed set of drift-type templates (see codegen.py),
not freeform text. The restrictions below guard against accidental
misuse (e.g. a bug in codegen producing code that touches the
filesystem) more than a deliberately malicious generator.
"""

# Deliberately small: no open, __import__, eval, exec, input, compile,
# getattr/setattr/delattr (limits introspection-based escapes), etc.
_SAFE_BUILTINS = {
    "None": None,
    "True": True,
    "False": False,
    "len": len,
    "str": str,
    "int": int,
    "float": float,
    "bool": bool,
    "dict": dict,
    "list": list,
    "tuple": tuple,
    "print": print,
}


class SandboxExecutionError(RuntimeError):
    """Raised when generated code fails to execute in the sandbox."""


def run_sandboxed(code: str, allowed_globals: dict) -> dict:
    """Execute generated code in a restricted environment.

    Args:
        code: Python source generated by codegen.py — expected to be a
            single expression statement calling one allowed function,
            e.g. "revoke_security_group_ingress(sg_id='...', rule='...')".
        allowed_globals: the mock remediation functions the generated
            code is permitted to call, e.g.
            {"revoke_security_group_ingress": mock_methods.revoke_security_group_ingress}.
            Nothing else is reachable from inside the sandbox.

    Returns:
        The mock function's own return value if the sandbox captured it
        (via a special `__result__` slot), else {"status": "success" or
        "failed", "message": ...} describing execution outcome.

    Raises:
        SandboxExecutionError: if the code raises during execution, or
            if it isn't a single call-expression statement.
    """
    import ast

    try:
        tree = ast.parse(code, mode="exec")
    except SyntaxError as exc:
        raise SandboxExecutionError(f"generated code is not valid Python: {exc}") from exc

    if len(tree.body) != 1 or not isinstance(tree.body[0], ast.Expr) or not isinstance(
        tree.body[0].value, ast.Call
    ):
        raise SandboxExecutionError(
            "sandbox only accepts a single function-call statement; "
            "refusing to run anything else"
        )

    call_node = tree.body[0].value
    if not isinstance(call_node.func, ast.Name) or call_node.func.id not in allowed_globals:
        raise SandboxExecutionError(
            f"generated code calls a function not in the allowed set: "
            f"{getattr(call_node.func, 'id', '<unknown>')!r}"
        )

    # Capture the call's return value by rewriting to `__result__ = <call>`.
    assign_node = ast.Assign(
        targets=[ast.Name(id="__result__", ctx=ast.Store())],
        value=call_node,
    )
    module = ast.Module(body=[assign_node], type_ignores=[])
    ast.fix_missing_locations(module)

    restricted_globals = {"__builtins__": dict(_SAFE_BUILTINS), **allowed_globals}
    local_scope: dict = {}

    try:
        exec(compile(module, filename="<aerodrift-generated>", mode="exec"), restricted_globals, local_scope)
    except Exception as exc:
        raise SandboxExecutionError(f"generated code raised during execution: {exc}") from exc

    result = local_scope.get("__result__")
    if isinstance(result, dict) and "status" in result:
        return result
    return {"status": "success", "message": "executed, no structured result returned", "raw_result": result}
